package com.barManager.entity;

public class BmAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_admin.Id
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_admin.USER_NAME
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_admin.PASS_WORD
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_admin.REMARK
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_admin.Id
     *
     * @return the value of bm_admin.Id
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_admin.Id
     *
     * @param id the value for bm_admin.Id
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_admin.USER_NAME
     *
     * @return the value of bm_admin.USER_NAME
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_admin.USER_NAME
     *
     * @param userName the value for bm_admin.USER_NAME
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_admin.PASS_WORD
     *
     * @return the value of bm_admin.PASS_WORD
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_admin.PASS_WORD
     *
     * @param passWord the value for bm_admin.PASS_WORD
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_admin.REMARK
     *
     * @return the value of bm_admin.REMARK
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_admin.REMARK
     *
     * @param remark the value for bm_admin.REMARK
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}