package com.barManager.entity;

public class BmCarousel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_carousel.Id
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_carousel.CAROUSEL_PATH
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    private String carouselPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_carousel.TYPE
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_carousel.Id
     *
     * @return the value of bm_carousel.Id
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_carousel.Id
     *
     * @param id the value for bm_carousel.Id
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_carousel.CAROUSEL_PATH
     *
     * @return the value of bm_carousel.CAROUSEL_PATH
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public String getCarouselPath() {
        return carouselPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_carousel.CAROUSEL_PATH
     *
     * @param carouselPath the value for bm_carousel.CAROUSEL_PATH
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public void setCarouselPath(String carouselPath) {
        this.carouselPath = carouselPath == null ? null : carouselPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_carousel.TYPE
     *
     * @return the value of bm_carousel.TYPE
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_carousel.TYPE
     *
     * @param type the value for bm_carousel.TYPE
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}