package com.barManager.entity;

public class BmOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.Id
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.ORDER_NUMBER
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.ORDER_PRODUCTID
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String orderProductid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.ORDER_PRICE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.CREATE_TIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.UPDATA_RIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String updataRime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_order.ORDER_TYPE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    private String orderType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.Id
     *
     * @return the value of bm_order.Id
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.Id
     *
     * @param id the value for bm_order.Id
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.ORDER_NUMBER
     *
     * @return the value of bm_order.ORDER_NUMBER
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.ORDER_NUMBER
     *
     * @param orderNumber the value for bm_order.ORDER_NUMBER
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.ORDER_PRODUCTID
     *
     * @return the value of bm_order.ORDER_PRODUCTID
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getOrderProductid() {
        return orderProductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.ORDER_PRODUCTID
     *
     * @param orderProductid the value for bm_order.ORDER_PRODUCTID
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setOrderProductid(String orderProductid) {
        this.orderProductid = orderProductid == null ? null : orderProductid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.ORDER_PRICE
     *
     * @return the value of bm_order.ORDER_PRICE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.ORDER_PRICE
     *
     * @param orderPrice the value for bm_order.ORDER_PRICE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setOrderPrice(String orderPrice) {
        this.orderPrice = orderPrice == null ? null : orderPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.CREATE_TIME
     *
     * @return the value of bm_order.CREATE_TIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.CREATE_TIME
     *
     * @param createTime the value for bm_order.CREATE_TIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.UPDATA_RIME
     *
     * @return the value of bm_order.UPDATA_RIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getUpdataRime() {
        return updataRime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.UPDATA_RIME
     *
     * @param updataRime the value for bm_order.UPDATA_RIME
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setUpdataRime(String updataRime) {
        this.updataRime = updataRime == null ? null : updataRime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_order.ORDER_TYPE
     *
     * @return the value of bm_order.ORDER_TYPE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_order.ORDER_TYPE
     *
     * @param orderType the value for bm_order.ORDER_TYPE
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }
}