package com.barManager.entity;

import java.util.Date;

public class BmOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_BUYER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String orderBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ADDRESS
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_TAGE
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String orderTage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_CONTENT
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String orderContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_MONEY
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private String orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    private Date orderTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_ID
     *
     * @return the value of BM_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_ID
     *
     * @param orderId the value for BM_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_BUYER
     *
     * @return the value of BM_ORDER.ORDER_BUYER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getOrderBuyer() {
        return orderBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_BUYER
     *
     * @param orderBuyer the value for BM_ORDER.ORDER_BUYER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderBuyer(String orderBuyer) {
        this.orderBuyer = orderBuyer == null ? null : orderBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ADDRESS
     *
     * @return the value of BM_ORDER.ADDRESS
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ADDRESS
     *
     * @param address the value for BM_ORDER.ADDRESS
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_TAGE
     *
     * @return the value of BM_ORDER.ORDER_TAGE
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getOrderTage() {
        return orderTage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_TAGE
     *
     * @param orderTage the value for BM_ORDER.ORDER_TAGE
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderTage(String orderTage) {
        this.orderTage = orderTage == null ? null : orderTage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_CONTENT
     *
     * @return the value of BM_ORDER.ORDER_CONTENT
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getOrderContent() {
        return orderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_CONTENT
     *
     * @param orderContent the value for BM_ORDER.ORDER_CONTENT
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent == null ? null : orderContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_MONEY
     *
     * @return the value of BM_ORDER.ORDER_MONEY
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public String getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_MONEY
     *
     * @param orderMoney the value for BM_ORDER.ORDER_MONEY
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderMoney(String orderMoney) {
        this.orderMoney = orderMoney == null ? null : orderMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_ORDER.ORDER_TIME
     *
     * @return the value of BM_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_ORDER.ORDER_TIME
     *
     * @param orderTime the value for BM_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }
}