package com.barManager.entity;

public class BmProducts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.Id
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_TYPEID
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private Integer productTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_PRICE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private String productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_PICTURE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private String productPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_COUNT
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private String productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_products.PRODUCT_DESCRIBE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    private String productDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.Id
     *
     * @return the value of bm_products.Id
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.Id
     *
     * @param id the value for bm_products.Id
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_NAME
     *
     * @return the value of bm_products.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_NAME
     *
     * @param productName the value for bm_products.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_TYPEID
     *
     * @return the value of bm_products.PRODUCT_TYPEID
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public Integer getProductTypeid() {
        return productTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_TYPEID
     *
     * @param productTypeid the value for bm_products.PRODUCT_TYPEID
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductTypeid(Integer productTypeid) {
        this.productTypeid = productTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_PRICE
     *
     * @return the value of bm_products.PRODUCT_PRICE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public String getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_PRICE
     *
     * @param productPrice the value for bm_products.PRODUCT_PRICE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice == null ? null : productPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_PICTURE
     *
     * @return the value of bm_products.PRODUCT_PICTURE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_PICTURE
     *
     * @param productPicture the value for bm_products.PRODUCT_PICTURE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture == null ? null : productPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_COUNT
     *
     * @return the value of bm_products.PRODUCT_COUNT
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public String getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_COUNT
     *
     * @param productCount the value for bm_products.PRODUCT_COUNT
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductCount(String productCount) {
        this.productCount = productCount == null ? null : productCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_products.PRODUCT_DESCRIBE
     *
     * @return the value of bm_products.PRODUCT_DESCRIBE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public String getProductDescribe() {
        return productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_products.PRODUCT_DESCRIBE
     *
     * @param productDescribe the value for bm_products.PRODUCT_DESCRIBE
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    public void setProductDescribe(String productDescribe) {
        this.productDescribe = productDescribe == null ? null : productDescribe.trim();
    }
}