package com.barManager.entity;

public class BmProductsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_productstype.Id
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_productstype.TYPE_NAME
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_productstype.TYPE_IMAGE
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    private String typeImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_productstype.REMARK
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_productstype.Id
     *
     * @return the value of bm_productstype.Id
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_productstype.Id
     *
     * @param id the value for bm_productstype.Id
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_productstype.TYPE_NAME
     *
     * @return the value of bm_productstype.TYPE_NAME
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_productstype.TYPE_NAME
     *
     * @param typeName the value for bm_productstype.TYPE_NAME
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_productstype.TYPE_IMAGE
     *
     * @return the value of bm_productstype.TYPE_IMAGE
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public String getTypeImage() {
        return typeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_productstype.TYPE_IMAGE
     *
     * @param typeImage the value for bm_productstype.TYPE_IMAGE
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public void setTypeImage(String typeImage) {
        this.typeImage = typeImage == null ? null : typeImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_productstype.REMARK
     *
     * @return the value of bm_productstype.REMARK
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_productstype.REMARK
     *
     * @param remark the value for bm_productstype.REMARK
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}