package com.barManager.entity;

public class BmUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_USER.ID
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_USER.USER_NAME
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_USER.PASS_WORD
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BM_USER.REMARK
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_USER.ID
     *
     * @return the value of BM_USER.ID
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_USER.ID
     *
     * @param id the value for BM_USER.ID
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_USER.USER_NAME
     *
     * @return the value of BM_USER.USER_NAME
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_USER.USER_NAME
     *
     * @param userName the value for BM_USER.USER_NAME
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_USER.PASS_WORD
     *
     * @return the value of BM_USER.PASS_WORD
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_USER.PASS_WORD
     *
     * @param passWord the value for BM_USER.PASS_WORD
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BM_USER.REMARK
     *
     * @return the value of BM_USER.REMARK
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BM_USER.REMARK
     *
     * @param remark the value for BM_USER.REMARK
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}