package com.barManager.dao;

import com.barManager.entity.BmAdmin;
import com.barManager.entity.BmUser;

public interface BmAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    int insert(BmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    int insertSelective(BmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    BmAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    int updateByPrimaryKeySelective(BmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_admin
     *
     * @mbggenerated Wed Mar 14 09:17:49 CST 2018
     */
    int updateByPrimaryKey(BmAdmin record);
    
    
    BmAdmin queryAdminByUsername(String username);
}