package com.barManager.dao;

import java.util.List;

import com.barManager.entity.BmCarousel;

public interface BmCarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    int insert(BmCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    int insertSelective(BmCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    BmCarousel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    int updateByPrimaryKeySelective(BmCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_carousel
     *
     * @mbggenerated Wed Mar 14 09:45:49 CST 2018
     */
    int updateByPrimaryKey(BmCarousel record);
    
    /**
     * 查询所有轮转图信息
     * @author chenyang
     * */
	List<BmCarousel> queryBmCarousels(Object object);
}