package com.barManager.dao;

import com.barManager.entity.BmOrder;

public interface BmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    int insert(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    int insertSelective(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    BmOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    int updateByPrimaryKeySelective(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_order
     *
     * @mbggenerated Thu Mar 15 10:23:42 CST 2018
     */
    int updateByPrimaryKey(BmOrder record);
}