package com.barManager.dao;

import com.barManager.entity.BmOrder;

public interface BmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    int insert(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    int insertSelective(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    BmOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    int updateByPrimaryKeySelective(BmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_ORDER
     *
     * @mbggenerated Wed Sep 20 15:40:54 CST 2017
     */
    int updateByPrimaryKey(BmOrder record);
}