package com.barManager.dao;

import java.util.List;

import com.barManager.entity.BmProducts;
import com.barManager.entity.BmProductsType;

public interface BmProductsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    int insert(BmProductsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    int insertSelective(BmProductsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    BmProductsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    int updateByPrimaryKeySelective(BmProductsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_productstype
     *
     * @mbggenerated Thu Mar 15 09:39:32 CST 2018
     */
    int updateByPrimaryKey(BmProductsType record);
    
    List<BmProductsType> queryBmProductsType(Object object);
}