package com.barManager.dao;

import java.util.List;

import com.barManager.entity.BmProducts;

public interface BmProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    int insert(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    int insertSelective(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    BmProducts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    int updateByPrimaryKeySelective(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_products
     *
     * @mbggenerated Thu Mar 15 10:43:51 CST 2018
     */
    int updateByPrimaryKey(BmProducts record);

	List<BmProducts> queryBmProducts(Object object);
}