package com.barManager.dao;

import com.barManager.entity.BmProducts;

public interface BmProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    int insert(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    int insertSelective(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    BmProducts selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    int updateByPrimaryKeySelective(BmProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_PRODUCTS
     *
     * @mbggenerated Wed Sep 20 15:40:26 CST 2017
     */
    int updateByPrimaryKey(BmProducts record);
}