package com.barManager.dao;

import com.barManager.entity.BmUser;

public interface BmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    int insert(BmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    int insertSelective(BmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    BmUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    int updateByPrimaryKeySelective(BmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BM_USER
     *
     * @mbggenerated Wed Sep 20 15:37:49 CST 2017
     */
    int updateByPrimaryKey(BmUser record);
}